server:
  port: 8000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: feed-service
            uri: http://localhost:8080
            predicates:
              Path=/feed/api/v1/**
springdoc:
  swagger-ui:
    urls:
      - name: "feed-service"
        url: http://localhost:8080/feed/api/v1/api-docs
